# Generated by Django 4.1.6 on 2023-02-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tg_usrename',
            new_name='tg_username',
        ),
    ]
